spring:
  profiles:
    active: prod

  # 타임존을 한국시간(Asia/Seoul)으로 고정
  time-zone: Asia/Seoul

server:
  # JSON 본문 크기 허용 설정
  tomcat:
    max-http-form-post-size: -1     # 폼/JSON 본문 크기 무제한
    max-swallow-size: -1            # 파일 업로드 등 버퍼 제한 해제
  max-http-request-header-size: 32KB  # (선택) 헤더 크기 여유 확보
