server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: medibear

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-withered-darkness-a1tmyqae-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_dan9lDkwSP5X

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
      timeout: 6000       # ì„ íƒì´ì§€ë§Œ ë„£ì–´ë‘ë©´ ì•ˆì •ì„± â†‘

cors:
  allowed:
    origins: "https://medibear.vercel.app"

fastapi:
  # ğŸ”¥ ì‹¤ì œ FastAPI ë°°í¬ URLë¡œ ë³€ê²½í•´ì•¼ í•¨!
  url: "https://medibearfastapi-production.up.railway.app"

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 1000000000
